### ISSUE TITLE
note about poweroff

### ISSUE THREAD

**Issue by ljm42** [selfhosters/selfhosters.net#8]
The poweroff note on this page:
  https://github.com/selfhosters/selfhosters.net/blob/master/docs/commands.md
isn't quite right:
```!!! note "Note" poweroff will gracefully shut everything down, even spin down the hard drives, but will not actually turn off the power supply.But there is a race condition in the code which could cause the system to power off before the Flash is updated indicating 'clean shutdown'. This can't cause data loss, but will cause parity-check to automatically start upon next reboot.```

There isn't a race condition. If the array is not able to shutdown cleanly, then there is likely an issue with your timeout settings. There are a few that need to be coordinated, see:
  https://forums.unraid.net/topic/69868-dealing-with-unclean-shutdowns
* VM Settings -> VM Shutdown timeout: must be long enough for VMs to shut down (including any updates a Windows VM decides to do while shutting down)
* Disk Settings -> Shutdown timeout: must be long enough for VMs to shut down, dockers to stop, and the array to stop. Once this timeout expires the array is forcibly stopped (thus causing an unclean shutdown)
* UPS Settings -> various timeouts: the system must be able to run on battery power for at least as long as the Disk Settings Shutdown timeout.

Also, I'm not sure the note about the power supply is accurate either. Pretty sure my system turns completely off.

**Comment by GilbN** [comment]
Thanks for the comment! The race condition stuff was grabbed from this forum comment. https://forums.unraid.net/topic/67-unraid-commands-for-all/?do=findComment&comment=2927

Maybe it's a bit outdated?

**Comment by ljm42** [comment]
I confirmed with Tom, that comment from 14 years ago no longer applies. That was for a very different version of Unraid.

**Comment by GilbN** [comment]
Thanks, replaced the note with information about timeout settings 👍 https://github.com/selfhosters/selfhosters.net/commit/529205f6b6c912d338f403409ce7aefa75045228
